apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress
spec:
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            name: mywppod
            labels:
                app: frontend
        spec:
            containers:
                - name: mywpcont
                  image: wordpress
                  envFrom:
                    - configMapRef:
                          name: wp-config
                  volumeMounts:
                    - mountPath: /var/www/html
                      name: wp-vol
            volumes:
                - name: wp-vol
                  persistentVolumeClaim:
                    claimName: wp-pvc

---
apiVersion: v1
kind: Service
metadata:
    name: wp-svc
spec:
    type: NodePort
    selector:
        app: frontend
    ports:
        - targetPort: 80
          port: 80
          nodePort: 30072


  
