apiVersion: v1
kind: PersistentVolume
metadata:
    name: wp-pv
spec:
    capacity:
        storage: 1G
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
        server: 172.31.2.27
        path: /wordpress
    mountOptions:
        - hard
            
