#kubectl label nodes worker02 type=mytest

apiVersion: apps/v1
kind: Deployment
metadata:
    name: website
spec:
    replicas: 10
    selector:
        matchLabels: 
            app: web
    template: 
        metadata:
           name: mypd
           labels:
              app: web
        spec:
            nodeSelector:
                type: mytest     
            containers:
                - name: mycnt
                  image: nginx
        
      
