apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 5
  selector:
    matchLabels:
      type: web
  template:
    metadata:
      name: mypod
      labels:
        type: web
    spec:
      containers:
        - name: mycon
          image: httpd
          volumeMounts:
            - name: abc
              mountPath: /usr/local/apache2/htdocs
      volumes:
        - name: abc
          persistentVolumeClaim:
            claimName: my-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  selector:
    type: web
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30081
