apiVersion: v1
kind: Service
metadata:
    name: my-nodeport-svc
spec: 
    type: NodePort
    selector:
        app: webon
    ports:
        - targetPort: 80
          port: 80
          nodePort: 30090
