apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-my-test
spec:
    capacity:
        storage: 1G
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
        path: /website
        server: 172.31.4.246
    mountOptions:
        - hard
        
