apiVersion: v1
kind: ReplicationController
metadata:
    name: my-replicationcontroller
spec:
    replicas: 5
    template:
        metadata:
            name: mypod
            labels:
                app: web
        spec:
            containers:
                - name: mycont1
                  image: nginx
